# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DailyPaper' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DailyPaper
	pod 'AFNetworking'
	pod 'Masonry'
	pod 'SDWebImage'
	pod 'MJRefresh'
  target 'DailyPaperTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DailyPaperUITests' do
    # Pods for testing
  end

end
